### ISSUE TITLE
Inline style violates Content Security Policy directive

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/hmpps-digital-prison-reporting-frontend#82]
Hello,

I'm seeing a CSP error in the reports page:

```
Refused to apply inline style because it violates the following Content Security Policy directive:
"style-src 'self' frontend-components-dev.hmpps.service.justice.gov.uk 'nonce-39db5c49ac1df30f4fe76adad6f7e864'". 
Either the 'unsafe-inline' keyword, a hash ('sha256-eIUqgPTKhr3+WsA7FtEp+r8ITeTom+YQ/XO6GMvUtjc='),
or a nonce ('nonce-...') is required to enable inline execution. 
Note that hashes do not apply to event handlers, style attributes and javascript:
navigations unless the 'unsafe-hashes' keyword is present.
```

I've added the following to the `styleSrc` to our helmet/CSP configuration and the error disappears:

```JavaScript
styleSrc: [
  "'self'",
  frontendComponentsHost,
  // DPR
  "'unsafe-hashes'",
  "'sha256-eIUqgPTKhr3+WsA7FtEp+r8ITeTom+YQ/XO6GMvUtjc='",
  // [...]
```

but this is probably brittle and maybe the library can be tweaked to avoid this.

**Comment by stalwartsolutions** [comment]
This is fixed in v3.7.2.

**Comment by xoen** [comment]
Thanks for sorting this out @stalwartsolutions - I was trying to play with this locally but I think the VPN is having some problems at the moment so I've created [a draft PR](https://github.com/ministryofjustice/hmpps-non-associations/pull/302) and hopefully later or on Monday I should be able to double check this :)

**Comment by xoen** [comment]
FYI: I tried this locally (VPN seems better today 😅) and I can confirm that error is gone even when I've removed those those `styleSrc` directives from the CSP 👍. Thanks again for sorting it ☺️
