### ISSUE TITLE
Chrome warning 'Third-party cookie will be blocked'

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/hmpps-digital-prison-reporting-frontend#83]
Hello,

I'm seeing this warning in the JS console of the browser but it only seems to show in a report page.

Issues tab says:

> Reading cookie in cross-site context will be blocked in future Chrome versions
Cookies with the SameSite=None; Secure and not Partitioned attributes that operate in cross-site contexts are third-party cookies. In future Chrome versions, reading third-party cookies will be blocked. This behavior protects user data from cross-site tracking.
Please refer to the article linked to learn more about preparing your site to avoid potential breakage.
2 cookies
3 requests
Learn more: Prepare for phasing out third-party cookies

and points to this page: [Prepare for phasing out third-party cookies](https://developers.google.com/privacy-sandbox/3pcd#report-issues).

![Screenshot 2024-03-26 at 12 00 07](https://github.com/ministryofjustice/hmpps-digital-prison-reporting-frontend/assets/238563/67df0a37-534d-48d1-b3a1-55430caa5f52)

I'm not quite sure what's causing this exactly but it seems like Chrome is planning to gradually blocking 3rd party cookies over time and this may lead to some functionality not working once they stop them for 100% of the users.

**Comment by stalwartsolutions** [comment]
Sorry, I keep coming back to this one and not making any ground on it.

I can't reproduce the issue in our apps that use the library, and I can't see anything in our codebase that might be causing it.

Is there any other information in Chrome about the request that might give us a hint?

**Comment by xoen** [comment]
Hi @stalwartsolutions, I checked `dev`/`prod` and I don't see this message neither, I only see it locally so maybe it is something to do with the way we run the service locally against `dev` services?

I'll close it then, you can always reopen in future if necessary.
